services:
  - type: web
    name: my-eco-web-project-frontend
    env: node
    buildCommand: 'pnpm install && pnpm build'
    startCommand: 'pnpm start'
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
  - type: web
    name: my-eco-web-project-backend
    env: node
    buildCommand: 'cd backend && pnpm install && pnpm build'
    startCommand: 'cd backend && pnpm start'
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
databases:
  - name: my-database
    plan: free
    region: oregon
